[tox]
envlist = py36, py37, py38


[testenv]
install_command = pip install --pre {opts} {packages}
whitelist_externals =
    unzip
    bash
deps =
    -rrequirements.txt

passenv =
      KAGGLE_USERNAME
      KAGGLE_KEY

setenv =
  PYTHONPATH=.

commands =
     kaggle datasets download -d vbookshelf/v2-plant-seedlings-dataset -p neural_network_model/datasets/
     unzip -o neural_network_model/datasets/v2-plant-seedlings-dataset.zip -d neural_network_model/datasets/v2-plant-seedlings-dataset
     python neural_network_model/train_pipeline.py
     pytest \
           -s \
           -v \
           {posargs:tests}
